package-lock.json, package.json, src/App.tsx, src/components/header/Header.style.ts, src/components/header/Header.tsx, src/components/sidebar/Sidebar.style.ts, src/components/sidebar/Sidebar.tsx, src/router/Router.style.ts, src/router/Router.tsx, src/styles/GlobalStyles.ts, src/styles/styled.d.ts, src/styles/theme.ts
```
[CHORE] reset CSS, theme 생성 / src 폴더 구조
```
1. styled-components  reset CSS 적용
2. styled-components ThemeProvider 적용
혹시 잘못 작성된 부분이 있으면 코멘트 부탁드립니다!
=> [CHORE] reset CSS, theme 생성

package-lock.json, package.json
=> [CHORE] react-icons 설치

package-lock.json, package.json, tsconfig.json, vite.config.ts
* import 할 때, `@src/`를 통해 경로를 지정할 수 있도록 수정
잘못 설정된 부분이 있다면 말씀해주세요!
=> [FIX]: config 파일 수정

package-lock.json, package.json, src/components/checkBox/CheckBox.style.ts, src/components/checkBox/CheckBox.tsx, src/components/datePicker/DatePicker.style.ts, src/components/datePicker/DatePicker.tsx, src/components/header/Header.style.ts, src/components/sidebar/Sidebar.style.ts, src/data/colorMap.ts, src/main.tsx, src/pages/planner/Planner.style.ts, src/pages/planner/Planner.tsx, src/pages/planner/components/inputForm/InputForm.style.ts, src/pages/planner/components/inputForm/InputForm.tsx, src/pages/planner/components/inputForm/RepeatDaySelector.style.ts, src/pages/planner/components/inputForm/RepeatDaySelector.tsx, src/pages/planner/components/timeLine/TimeLine.style.ts, src/pages/planner/components/timeLine/TimeLine.tsx, src/pages/planner/components/todoBox/TodoBox.style.ts, src/pages/planner/components/todoBox/TodoBox.tsx, src/router/Router.style.ts, src/router/Router.tsx, src/styles/styled.d.ts, src/styles/theme.ts, vite.config.ts
* 플래너 페이지 '오늘의 계획표' 파트의 UI 구현
크롬 개발자도구로 기기 전환했을때 하단에 여백이 생기는데, 
화면에 정상적으로 작동하는지 확인해주시면 감사하겠습니다!
- close #5
=> [FEAT] 플래너 페이지 '오늘의 계획표' UI 구현

src/pages/study-room/StudyRooms.tsx, src/pages/study-room/components/filter/CheckBox.style.ts
StudyRooms.tsx에 있는 CheckBox 컴포넌트 경로 수정
Checkbox 컴포넌트가 2개가 있는데 이름을 바꾸는게 좋을까요?
- close #16
=> [FIX] StudyRooms page CheckBox 컴포넌트 경로 수정

src/components/layout/Layout.tsx, src/components/rsidebar/RSidebar.style.ts, src/components/rsidebar/RSidebar.tsx, src/pages/privateStudyRoom/PrivateStudyRoom.tsx, src/router/Router.tsx
- 우측 사이드바 테마 설정
- 일단 경로가 /study-room으로 시작하는 모든 곳에 우측 사이드바 처럼 나오게 설정해놨습니다.
- close #19
=> [FEAT] 우측 사이드바 테마 설정

package-lock.json, package.json, src/App.tsx, src/apis/planners.api.ts, src/components/checkBox/CheckBox.style.ts, src/components/checkBox/CheckBox.tsx, src/components/rsidebar/RSidebar.style.ts, src/components/rsidebar/RSidebar.tsx, src/components/rsidebar/chatRoom/ChatRoom.style.ts, src/components/rsidebar/chatRoom/ChatRoom.tsx, src/components/rsidebar/todos/Todos.style.ts, src/components/rsidebar/todos/Todos.tsx, src/components/rsidebar/utils/dateFormat.ts, src/models/studyRoomTodos.model.ts, src/pages/planner/Planner.style.ts, src/pages/planner/components/todoBox/TodoBox.style.ts, src/pages/planner/components/todoBox/TodoBox.tsx, src/stores/studyRoom.store.ts, src/styles/mixins.ts, src/styles/theme.ts
* RSideBar UI 구현
* RSideBar-할 일 구현
* 임시 API 연동 
리팩토링, 오동작, UI 등 개선사항 리뷰해주시면 감사하겠습니다!
* 월요일 회의 진행 후, CheckBox API 연동
* 채팅탭 구현
=> [FEAT] 스터디룸 RSideBar-할일 구현

src/components/header/Header.style.ts, src/components/header/Header.tsx, src/components/layout/Layout.style.ts, src/components/layout/Layout.tsx, src/components/sidebar/Sidebar.style.ts, src/components/sidebar/Sidebar.tsx, src/pages/profile/ProfilePage.style.ts, src/pages/profile/ProfilePage.tsx, src/pages/profile/components/BasicInfo.tsx, src/pages/profile/components/MyProfile.tsx, src/router/Router.tsx
헤더, 사이드바, 프로필 페이지 구현하였습니다.
다른 사이트들 참고하여 디자인 수정하였습니다. 확인 부탁드립니다!
- close #10
=> [FEAT] 헤더, 사이드바, 프로필 페이지 구현

src/components/rsidebar/chatRoom/ChatRoom.style.ts, src/components/rsidebar/chatRoom/ChatRoom.tsx, src/components/rsidebar/chatRoom/chatting/Chatting.style.ts, src/components/rsidebar/chatRoom/chatting/Chatting.tsx, src/components/rsidebar/todos/Todos.tsx, src/models/chat.model.ts
RSidebar 채팅UI 구현하였습니다.
웹소켓과의 연결은 안된 상태입니다.
오동작이나 개선사항 있으면 코멘트 부탁드립니다!
Closes #21
=> [FEAT] RSidebar 채팅UI 구현

src/pages/study-room/components/form/CreateStudyRoomForm.tsx
- 공부방 생성 모달 최대 인원 타입 수정
maxNum 데이터 string -> number 타입 변환 필요 
- 공부방 생성 되는 것 확인 했는데 다시 한 번 확인 부탁드립니다!
=> [HOTFIX] maxNum 데이터 타입 변환

src/pages/study-room/components/form/CreateStudyRoomForm.tsx
=> [FIX] 공부방 생성시 방 이동

src/pages/study-room/components/form/PasswordInput.style.ts, src/pages/study-room/components/form/PasswordInput.tsx, src/pages/study-room/components/item/StudyGrid.style.ts, src/pages/study-room/components/item/StudyGrid.tsx
- 비공개 스터디름 입장시 비밀번호 입력 모달창 UI 개선
- 검색 결과가 없을 경우 뜨는 UI
- close #56
=> [FEAT] 비공개 스터디룸 입장 비밀번호 UI 및 검색 결과 없을 경우 UI

src/pages/study-room/components/item/StudyGrid.style.ts, src/pages/study-room/components/item/StudyGrid.tsx, src/router/Router.tsx, src/types/studyRoom.ts
공부방 조회 페이지 무한스크롤 구현
develop의 공부방 조회 페이지와 충돌이 잘 해결됐는지 확인부탁드립니다!
=> [FEAT] 공부방 조회 페이지 무한스크롤 구현

src/apis/apiRoutes.ts, src/apis/planners.api.ts, src/apis/ranking.api.ts, src/components/datePicker/DatePicker.tsx, src/components/loader/Loader.style.ts, src/components/loader/Loader.tsx, src/models/studyRoomTodos.model.ts, src/pages/planner/Planner.style.ts, src/pages/planner/Planner.tsx, src/pages/planner/components/inputForm/InputForm.style.ts, src/pages/planner/components/inputForm/InputForm.tsx, src/pages/planner/components/todoBox/TodoBox.style.ts, src/pages/planner/components/todoBox/TodoBox.tsx, src/pages/ranking/Ranking.tsx, src/pages/ranking/components/RankingBoard.style.ts, src/pages/ranking/components/RankingBoard.tsx, src/styles/GlobalStyles.ts, src/types/ranking.ts
* 플래너페이지 총시간 API 연결
* 랭킹페이지 API 연결
* 플래너 수정 요청시의 데이터 수정
* global 폰트 적용
* 기타 CSS 수정
* 잘못된 Loader 컴포넌트 렌더링 수정
수정해야 할 부분 있으면 코멘트 부탁드립니다!
- Closes #63
=> [FEAT] 플래너페이지 총시간 API, 랭킹페이지 API 연동

src/components/sidebar/Sidebar.style.ts, src/pages/ranking/Ranking.style.ts, src/pages/ranking/Ranking.tsx, src/pages/ranking/components/RankingBoard.style.ts, src/pages/ranking/components/RankingBoard.tsx
* 로그인했을 때 자신의 랭킹 표시, 비로그인 시 표시하지 않도록 수정
* 기타 css 수정
화면에 정상적으로 출력되는지 확인 부탁드립니다
- Closes #65
=> [FIX] 랭킹페이지 UI 수정 

src/apis/apiRoutes.ts, src/apis/image.api.ts, src/apis/users.api.ts, src/components/header/Header.style.ts, src/components/header/Header.tsx, src/pages/profile/components/MyProfile.tsx, src/pages/study-room/components/imageUpload/ImageUpload.tsx, src/stores/auth.store.ts
- 드롭다운 닫았지만 여전히 클릭 되는 오류 해결
- 이미지 업로드 부분(프로필, 스터디룸 생성) 서버 연동
- 프로필 수정 후, 수정된 프로필 조회 기능 추가(백엔드 최신 PR # 39 동기화 필요)
- 이미지 서버 제대로 작동하는 지 한 번 더 테스트 부탁드려요!
- close #68
=> [FIX] 드롭다운 버그 해결 및 이미지 서버 연동

src/pages/home/components/my/todo/HomeTodo.tsx, src/pages/study-room/components/item/StudyGrid.style.ts, src/pages/study-room/components/item/StudyGrid.tsx
스터디룸 조회 Loading 스타일 수정
HomeTodo reactquery 사용
=> [REFACTOR] 스터디룸 조회 Loading 스타일 및 HomeTodo reactquery 변경

src/components/button/SCreateButton.tsx
=> [FIX] 배포를 위한 수정

src/components/rsidebar/RSidebar.tsx, src/pages/multiStudyRoom/component/StudyRoomNotice.tsx, src/pages/multiStudyRoom/multiStudyRoomContent/MultiStudyRoomContent.tsx
[fix] #pr45 버그 수정
- pr45 버그 수정
=> [fix] #pr45 버그 수정

src/components/studyProfileBox/StudyProfileBox.style.ts, src/components/studyProfileBox/StudyProfileBox.tsx, src/pages/multiStudyRoom/multiStudyRoomContent/MultiStudyRoomContent.style.ts, src/pages/multiStudyRoom/multiStudyRoomContent/MultiStudyRoomContent.tsx
* 공부방 페이지 방장 아이콘 추가
- close #78
=> [FEAT] 공부방 페이지 방장 아이콘 추가

src/components/rsidebar/todos/Todos.tsx, src/pages/multiStudyRoom/component/updateStudyRoomForm/UpdateStudyRoomForm.tsx, src/pages/multiStudyRoom/multiStudyRoomContent/MultiStudyRoomContent.tsx
[REFACTOR] 스터디룸 세팅 관련 코드 수정
- 스터디룸 세팅 관련 코드 수정
- 할 일 날짜가 오늘인 것만 선택 가능하게 변경
=> [REFACTOR] 스터디룸 세팅 관련 코드 수정

src/components/rsidebar/todos/Todos.tsx, src/pages/multiStudyRoom/component/updateStudyRoomForm/UpdateStudyRoomForm.tsx, src/pages/multiStudyRoom/multiStudyRoomContent/MultiStudyRoomContent.tsx, src/pages/privateStudyRoom/privateStudyRoomContent/PrivateStudyRoomContent.tsx
=> [FIX] socket 메세지 res 타입 fix

src/pages/home/components/home-studyrooms/item/HomeStudyItem.style.ts
비로그인시 홈에서 보이는 StudyRoom 이름 말 줄임표 되게 설정
=> [FIX] 비로그인시 홈에서 보이는 StudyRoom 스타일 수정

src/pages/statistics/all/AllStatisticsPage.style.ts, src/pages/statistics/all/components/myLineChart/MyLineChart.style.ts, src/pages/statistics/all/components/myLineChart/MyLineChart.tsx, src/pages/study-room/components/item/StudyItem.style.ts
- 전체 통계 페이지 가로 스크롤 생기는 부분 조정
- 사용자 경험을 위해 화살표 위치 이동, 커서 포인터 추가
=> [FIX] 가로 스크롤 조정
